name: Continuous integration
on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: yusancky/setup-typst@v2
        id: setup-typst
        with:
          version: 'latest'
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python tests/tools/run_tests.py
